broker_details:
  mqtt_ip: localhost
  mqtt_port: 1883
topics:
- name: hmi_request
  topic: churchill/ui/ui_1/instruction
  is_trigger: true
  is_subscribe: true
- name: request_command
  topic: churchill/depth_analysis/search/sku_data
  is_subscribe: true
  is_trigger: false
- name: database_output
  topic: churchill/database/search/matching_sku
  is_subscribe: False,
  is_trigger: false
- name: depth_data
  topic: churchill/camera/depth_1/image
  is_subscribe: true
  is_trigger: false
- name: colour_data
  topic: churchill/camera/colour_1/image
  is_subscribe: true
  is_trigger: false
database:
- file_location: C:\Users\Churchill-01\churchill\service-orchestrator\data\database\test_database.db
  database_name: test_database
  search_threshold: 200
  tables:
  - database_table: test_table
    columns:
    - id
    - depth
    - perimeter
    - radius
    - depth_data
    - colour_data
    - sku
    searchable_columns:
    - depth
    - perimeter
    - radius
