# Broker connections  ---------------------------------------
broker_details:
  mqtt_ip: localhost
  mqtt_port: 1883

# Database connections ---------------------------------------
database: [
  {
    file_location: "database/test_database.db",
    database_name: "test_database",
    search_threshold: 20,
    tables: [
      {
        database_table: "test_table"
      }
    ]
  }
]

# MQTT options ---------------------------------------
topics: [
  {
    name: "add_to_table",
    topic: "test/database/add/sku_data",
    is_subscribe: True,
    is_trigger: True
  },
  {
    name: "search_table",
    topic: "test/database/search/sku_data",
    is_subscribe: True,
    is_trigger: True
  },
  {
    name: "database_output",
    topic: "test/database/search/matching_sku",
    is_subscribe: False,
    is_trigger: False
  },
  {
    name: "depth_data",
    topic: "test/image/depth_image",
    is_subscribe: True,
    is_trigger: False
  },
  {
    name: "colour_data",
    topic: "test/image/colour_image",
    is_subscribe: True,
    is_trigger: False
  }
]